# Generated by Django 2.2 on 2020-04-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='p_user',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='p_user',
            name='origin',
        ),
    ]
