# Generated by Django 2.2 on 2020-04-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_auto_20200406_0011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
    ]
