# Generated by Django 2.2 on 2020-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_delete_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('pincode', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=40, null=True)),
                ('state', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'Location',
            },
        ),
    ]
