# Generated by Django 2.2 on 2020-04-06 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
    ]
