# Generated by Django 2.2 on 2020-04-07 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_auto_20200407_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='p_user',
            field=models.ForeignKey(default='9925244839', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
