# Generated by Django 2.2 on 2020-04-07 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_book_p_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
