# Generated by Django 2.2 on 2020-04-07 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0012_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('pod', models.CharField(max_length=11, null=True, primary_key=True, serialize=False, unique=True)),
                ('booktype', models.CharField(max_length=6, null=True)),
                ('branch', models.CharField(max_length=3, null=True)),
                ('time', models.DateTimeField(auto_now_add=True, null=True)),
                ('destination', models.CharField(max_length=15, null=True)),
                ('nop', models.IntegerField()),
                ('weight', models.CharField(max_length=11, null=True)),
                ('amount', models.CharField(max_length=11, null=True)),
                ('value', models.CharField(blank=True, max_length=11, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('p_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='Booking.party')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Booking.party')),
            ],
            options={
                'db_table': 'Booking',
            },
        ),
    ]
