# Generated by Django 2.2 on 2020-04-08 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0014_price_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='name',
        ),
        migrations.RemoveField(
            model_name='price',
            name='name',
        ),
        migrations.AddField(
            model_name='party',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.price'),
        ),
        migrations.AddField(
            model_name='price',
            name='type',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
