# Generated by Django 2.2 on 2020-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0015_auto_20200408_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
