# Generated by Django 2.2 on 2020-04-08 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0016_party_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='credit',
        ),
    ]
