# Generated by Django 2.2 on 2020-04-08 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0017_delete_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='price',
            field=models.ForeignKey(blank=True, default='10', null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.price'),
        ),
    ]
