# Generated by Django 2.2 on 2020-04-09 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0018_auto_20200408_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='price',
            field=models.ForeignKey(blank=True, default='10', on_delete=django.db.models.deletion.CASCADE, to='Booking.price'),
        ),
    ]
