# Generated by Django 2.2 on 2020-04-09 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0020_auto_20200409_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='price',
        ),
        migrations.RemoveField(
            model_name='price',
            name='type',
        ),
    ]
